export const LOAD_CAMERA_ROLL_IMAGES = "LOAD_CAMERA_ROLL_IMAGES"
export const SAVE_TO_CAMERA_ROLL = "SAVE_TO_CAMERA_ROLL"

export const FIREBASE_UPLOAD_IMAGE = "FIREBASE_UPLOAD_IMAGE"
export const FIREBASE_DOWNLOAD_IMAGE = "FIREBASE_DOWNLOAD_IMAGE"
