export const LOAD_CAMERA_ROLL_IMAGES = "LOAD_CAMERA_ROLL_IMAGES"
export const SAVE_TO_CAMERA_ROLL = "SAVE_TO_CAMERA_ROLL"

export const FIREBASE_UPLOAD_IMAGE = "FIREBASE_UPLOAD_IMAGE"
export const FIREBASE_DOWNLOAD_IMAGE = "FIREBASE_DOWNLOAD_IMAGE"

export const VYBE_TRENDING_POSTS = "VYBE_TRENDING_POSTS"
export const VYBE_LATEST_POSTS = "VYBE_LATEST_POSTS"
export const VYBE_HOT_POSTS = "VYBE_HOT_POSTS"
export const VYBE_GET_POSTS = "VYBE_HOT_POSTS"
