# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'vybe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for vybe

  pod 'AppAuth', '>= 0.94'
  pod 'HockeySDK', '~> 5.1.4'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

end

