# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate the ios ipa"
  lane :build do
    match(
      type: "development",
      git_url: "git@github.com:deusd/vibranium.git",
      username: "deusduke@gmail.com",
      app_identifier: "*"
    )
    gym
  end
end
